### ISSUE TITLE
Tracking Service 성능 개선에 있어서 고민

### ISSUE THREAD

**Issue by kimgunwooo** [team-chang-ppo/location_tracking_module_backend#4]
## 🤷 토의 주제
서비스 특성상 데이터가 들어와서 DB에 적재됨과 동시에 그 정보를 읽기를 원한다.
여기서 성능 개선을 어떤 것을 할 수 있을까??

## 📄 자신의 생각
1. DB 인덱싱
	- read와 write의 작업량이 동일해서 적용해야할지 고민
	- read 시에는 빨라지지만, write 작업에선 느려져서..
2. 캐싱
	- 인메모리 DB를 사용해서 캐싱을 한다고 했을때
	- 현재는 DB에 데이터를 적재함과 동시에 다른 사용자가 그 정보를 읽기를 원한다.
	- 그리고 정보를 한번 받아오면 같은 데이터는 다시 원하지도 않음.
	- 미리 Redis에 요청할 것 같은 정보를 넣어줄 수도 없고, 그냥 거쳐가는 용도로만 사용될거같은데, 그럼 굳이 사용해야 할까??
3. 배치
	- 사용자 1명이라고 보면, 3초에 1번씩 POST 요청이 들어와서 DB에 적재하고, 다른 사용자가 3초에 1번씩 GET 요청을 보냄
	- 그렇다면 3초안에 들어오는 POST 요청, DB 적재 요청을 모아서 3초마다 한꺼번에 적용해주면 조금 성능이 개선되지 않을까
	- GET요청 또한 한꺼번에 처리..?
4) 비동기 처리
	- 외부 메시지 브로커 사용?
	- 유실에 대한 걱정은 크게 안해도 될 듯 하다
	- 하지만, 순서에 대한 걱정은 해야 할 듯.
	- 거의 지식이 없긴한데, 비동기 처리가 나쁘지 않아 보인다.

## 👄 같이 생각했으면 하는 점
4가지 안을 제시하고, 제 생각을 간단하게 정리해봤습니다.
제가 생각하기엔 배치나 비동기 처리 쪽이 맞는거 같은데 다른 분들 생각은 어떠신가요??
혹시 제가 생각한 부분에 있어서 틀린 점이 있으면 **시원한 피드백** 해주시면 감사하겠습니다!

아 물론 websocket 사용하면 실시간 처리가 가능하긴한데, 폴링을 사용한 요청이 가장 핵심이라고 생각해 사용자가 가장 많이 사용하지 않을까 싶어서 성능 개선을 하고, websocket은 추후 개발할 생각입니다!

**Comment by onjik** [comment]
캐싱을 요청이 왔을 때가 아니라, post요청시 그냥 set으로 캐시를 설정해버리면 어떨까요
그리고 읽을 때 만약 현재 위치 GET이라면, 바로 캐시에서 읽고, 없을 경우 db 조회하는 식으로

**Comment by kimgunwooo** [comment]
> 캐싱을 요청이 왔을 때가 아니라, post요청시 그냥 set으로 캐시를 설정해버리면 어떨까요
그리고 읽을 때 만약 현재 위치 GET이라면, 바로 캐시에서 읽고, 없을 경우 db 조회하는 식으로

@onjik 피드백 감사합니다 형님! 
궁금한 점이 있는데 만약 사용자가 증가하면 post 요청도 기하급수적으로 늘어날텐데 redis에 post 요청마다 저장해버리면 메모리가 터질 걱정은 없을까요?? -> 이 문제는 분산처리까지 고민해야 하겠죠??

**Comment by onjik** [comment]
> 궁금한 점이 있는데 만약 사용자가 증가하면 post 요청도 기하급수적으로 늘어날텐데 redis에 post 요청마다 저장해버리면 메모리가 터질 걱정은 없을까요?? -> 이 문제는 분산처리까지 고민해야 하겠죠??

최신 위치만 SET으로 덮어 씌우면 많이는 안쓸일 거같은데, 히스토리는 db 저장하고, 최신 위치만 SET
