### ISSUE TITLE
API 응답 구조를 통일하기 위한 방안 논의

### ISSUE THREAD

**Issue by joon6093** [team-chang-ppo/location_tracking_module_backend#5]
## 🤷 토의 주제
API 응답 구조를 통일하기 위한 방안 논의

## 📄 자신의 생각
예외 코드만 전달하는 방식을 채택할 경우, 프론트엔드에서 예외 메시지를 결정하게 되므로 예외 상황에 대한 문서화가 필요하며, 이는 관리의 복잡성을 증가시킬 수 있다.

## 👄 같이 생각했으면 하는 점
- 예외 처리 방식 선택
  - 예외 코드와 예외 메시지를 함께 백엔드에서 반환하여, 예외 처리에 대한 책임을 백엔드가 전적으로 맡는 방식
  - 예외 코드만 반환하고, 프론트엔드에서 이에 맞는 예외 메시지를 표시하는 방식

- correlation_id (MDC) 추가?

**Comment by onjik** [comment]
예외 처리가 꼭 팝업만 있는게 아니라서 결국 프론트엔드에서 코드 마다 작업을 해줘야할듯
예를 들어, 결제시 잔액이 부족한 경우 popup + 결제 초기화 가 필요하고
이메일 validation에 실패한 경우, 그냥 email Input box만 빨강으로 변하고 다시 입력하게 해야하는 것처럼

**Comment by joon6093** [comment]
예외 상황에 대한 문서화도 하고 예외 메시지도 반환 해야겟네요

**Comment by joon6093** [comment]
4월 2일 (화) 회의 시간에 이야기 해보죠
